//Source code generated by AppGPT (www.appgpt.tech)
//to be autogenerated as template, one per resource
import { Entity, Column, PrimaryGeneratedColumn } from 'typeorm';

@Entity('Clients')
export class ClientsEntity {
  @PrimaryGeneratedColumn()
  id: number;

  @Column('text', { nullable: true })
  Name: string;

  @Column('text', { nullable: true })
  Email: string;

  @Column('text', { nullable: true })
  Password: string;

  @Column('integer', { nullable: true })
  Therapist: number;

  @Column('integer', { nullable: true })
  MoodScale: number;

  @Column('bool', { nullable: true })
  PanicButton: boolean;

  @Column('integer', { nullable: true })
  CBTExercisesFrequency: number;

  @Column('integer', { nullable: true })
  MindfulnessExercisesFrequency: number;
}
