//Source code generated by AppGPT (www.appgpt.tech)
//to be autogenerated as template, one per resource
import { Entity, Column, PrimaryGeneratedColumn } from 'typeorm';

@Entity('Exercises')
export class ExercisesEntity {
  @PrimaryGeneratedColumn()
  id: number;

  @Column('text', { nullable: true })
  Title: string;

  @Column('text', { nullable: true })
  Description: string;

  @Column('text', { nullable: true })
  Type: string;

  @Column('integer', { nullable: true })
  Duration: number;

  @Column('text', { nullable: true })
  DifficultyLevel: string;
}
