//Source code generated by AppGPT (www.appgpt.tech)
//to be autogenerated as template, one per resource
import { Entity, Column, PrimaryGeneratedColumn } from 'typeorm';

@Entity('MoodEntries')
export class MoodEntriesEntity {
  @PrimaryGeneratedColumn()
  id: number;

  @Column('integer', { nullable: true })
  Client: number;

  @Column('date', { nullable: true })
  Date: Date;

  @Column('integer', { nullable: true })
  MoodScaleValue: number;

  @Column('text', { nullable: true })
  Notes: string;
}
