//Source code generated by AppGPT (www.appgpt.tech)
//to be autogenerated as template, one per resource
import { Entity, Column, PrimaryGeneratedColumn } from 'typeorm';

@Entity('Therapists')
export class TherapistsEntity {
  @PrimaryGeneratedColumn()
  id: number;

  @Column('text', { nullable: true })
  Name: string;

  @Column('text', { nullable: true })
  Email: string;

  @Column('text', { nullable: true })
  Password: string;

  @Column('text', { nullable: true })
  Specialization: string;

  @Column('text', { nullable: true })
  LicenseNumber: string;

  @Column('text', { nullable: true })
  ContactNumber: string;
}
