//Source code generated by AppGPT (www.appgpt.tech)
import {
  Datagrid,
  List,
  EditButton,
  Edit,
  SimpleForm,
  Create,
  SelectColumnsButton,
  DatagridConfigurable,
  TopToolbar,
  CreateButton,
  ExportButton,
  FilterButton,
  //Field controls
  BooleanField,
  DateField,
  EmailField,
  ImageField,
  NumberField,
  ReferenceField,
  TextField,
  UrlField,
  //Input controls
  BooleanInput,
  DateInput,
  EmailInput,
  ImageInput,
  NumberInput,
  ReferenceInput,
  TextInput,
  UrlInput,
  PasswordInput,
} from 'react-admin';
import { useRecordContext } from 'react-admin';
import { Grid } from '@mui/material';
const ReadOnlyPasswordField = ({ record, source }) => {
  // You can customize the way you display the password here, e.g., mask it with asterisks
  const maskedPassword = '********';

  return <span>{maskedPassword}</span>;
};
const ListActions = () => (
  <TopToolbar>
    <FilterButton />
    <CreateButton />
    <ExportButton />
    <SelectColumnsButton />
  </TopToolbar>
);
const ClientsTitle = () => {
  const record = useRecordContext();
  return <span>Clients {record ? `"${record.Name}"` : ''}</span>;
};

export const ClientsList = () => (
  <List actions={<ListActions />} filters={ResourceFilters}>
    <DatagridConfigurable>
      <TextField source="Name" />
      <EmailField source="Email" />
      <ReadOnlyPasswordField source="Password" />
      <ReferenceField source="Therapist" reference="Therapists" />
      <NumberField source="MoodScale" />
      <BooleanField source="PanicButton" />
      <NumberField source="CBTExercisesFrequency" />
      <NumberField source="MindfulnessExercisesFrequency" />
      <EditButton />
    </DatagridConfigurable>
  </List>
);

export const ClientsEdit = () => (
  <Edit title={<ClientsTitle />}>
    <SimpleForm>
      <Grid container rowSpacing={1} columnSpacing={{ xs: 1, sm: 2, md: 5 }}>
        <Grid item xs={4}>
          <TextInput source="Name" />
        </Grid>
        <Grid item xs={4}>
          <TextInput source="Email" />
        </Grid>
        <Grid item xs={4}>
          <PasswordInput source="Password" />
        </Grid>
        <Grid item xs={4}>
          <ReferenceInput source="Therapist" reference="Therapists" />
        </Grid>
        <Grid item xs={4}>
          <NumberInput source="MoodScale" />
        </Grid>
        <Grid item xs={4}>
          <BooleanInput source="PanicButton" />
        </Grid>
        <Grid item xs={4}>
          <NumberInput source="CBTExercisesFrequency" />
        </Grid>
        <Grid item xs={4}>
          <NumberInput source="MindfulnessExercisesFrequency" />
        </Grid>
      </Grid>
    </SimpleForm>
  </Edit>
);

export const ClientsCreate = () => (
  <Create>
    <SimpleForm>
      <Grid container rowSpacing={1} columnSpacing={{ xs: 1, sm: 2, md: 5 }}>
        <Grid item xs={4}>
          <TextInput source="Name" />
        </Grid>
        <Grid item xs={4}>
          <TextInput source="Email" />
        </Grid>
        <Grid item xs={4}>
          <PasswordInput source="Password" />
        </Grid>
        <Grid item xs={4}>
          <ReferenceInput source="Therapist" reference="Therapists" />
        </Grid>
        <Grid item xs={4}>
          <NumberInput source="MoodScale" />
        </Grid>
        <Grid item xs={4}>
          <BooleanInput source="PanicButton" />
        </Grid>
        <Grid item xs={4}>
          <NumberInput source="CBTExercisesFrequency" />
        </Grid>
        <Grid item xs={4}>
          <NumberInput source="MindfulnessExercisesFrequency" />
        </Grid>
      </Grid>
    </SimpleForm>
  </Create>
);

const ResourceFilters = [
  <TextInput source="q" label="Search" alwaysOn />,
  ,
  ,
  ,
  <ReferenceInput
    source="Therapist"
    label="Therapist"
    reference="Therapists"
    alwaysOn
  />,
  ,
  ,
  ,
  ,
];
