//Source code generated by AppGPT (www.appgpt.tech)
import { Card, CardContent, CardHeader } from '@mui/material';
export const Dashboard = () => (
  <Card>
    <CardHeader title="MindfulProgress" />
    <CardContent>
      The platform involves the development of a user-friendly mobile
      application that enhances the therapeutic process by providing continuous
      and personalised support to individuals undergoing therapy. It also
      includes a simple web-based dashboard for therapists to monitor client
      progress and assign tasks. The primary objective is to help bridge the
      gaps between therapy sessions, ensuring clients remain engaged,
      accountable, and supported. The platform will include but not be limited
      to: • Therapists can assign tasks and exercises to clients, set deadlines,
      and monitor completion. Clients provide feedback on their mental state
      before and after activities. • Clients can log their mood throughout the
      day using a simple scale. This data helps identify emotional patterns and
      triggers, offering valuable insights. • A panic button will provide
      immediate support during crises with access to preferred exercises and
      personalised quotes. • CBT and mindfulness exercises prescribed by
      therapists, with adjustable frequency. • Timely reminders will ensure
      clients complete tasks and mood tracking entries, integrating therapeutic
      activities into daily routines. The project will start with a literature
      review on the integration of digital tools in therapeutic practices,
      focusing on engagement, accountability, self-reflection, and crisis
      support. It will be followed by extensive research to gather accurate and
      up-to-date requirements from both therapists and clients through surveys,
      and a review of existing digital mental health applications to identify
      gaps and areas for improvement. This information will be organised and
      integrated into the application. The student will then use appropriate
      tools to develop the application. The final stages will involve testing
      and evaluation of the responsive application.
      <p>
        Built with{' '}
        <a
          href="https://www.appgpt.tech"
          target="_blank"
          rel="noopener noreferrer"
        >
          AppGPT
        </a>
      </p>
    </CardContent>
  </Card>
);
