//Source code generated by AppGPT (www.appgpt.tech)
let data: any = {
  defaultData: {
    Therapists: [
      {
        Name: 'Dr. Emma Johnson',
        Email: 'emma.johnson@example.com',
        Password: 'password123',
        Specialization: 'Clinical Psychology',
        LicenseNumber: 'PSY123456',
        ContactNumber: '555-0100',
      },
      {
        Name: 'Dr. Alex Smith',
        Email: 'alex.smith@example.com',
        Password: 'password456',
        Specialization: 'Cognitive Behavioral Therapy',
        LicenseNumber: 'CBT789101',
        ContactNumber: '555-0200',
      },
      {
        Name: 'Dr. Sophia Lee',
        Email: 'sophia.lee@example.com',
        Password: 'password789',
        Specialization: 'Family Therapy',
        LicenseNumber: 'FAM111213',
        ContactNumber: '555-0300',
      },
      {
        Name: 'Dr. Michael Brown',
        Email: 'michael.brown@example.com',
        Password: 'password321',
        Specialization: 'Psychiatry',
        LicenseNumber: 'PSY141516',
        ContactNumber: '555-0400',
      },
      {
        Name: 'Dr. Isabella Garcia',
        Email: 'isabella.garcia@example.com',
        Password: 'password654',
        Specialization: 'Child Psychology',
        LicenseNumber: 'CHP171819',
        ContactNumber: '555-0500',
      },
    ],
    Clients: [
      {
        Name: 'Alex Johnson',
        Email: 'alex.johnson@example.com',
        Password: 'password123',
        Therapist: 1,
        MoodScale: 3,
        PanicButton: true,
        CBTExercisesFrequency: 2,
        MindfulnessExercisesFrequency: 4,
      },
      {
        Name: 'Sam Taylor',
        Email: 'sam.taylor@example.com',
        Password: 'password456',
        Therapist: 2,
        MoodScale: 4,
        PanicButton: false,
        CBTExercisesFrequency: 3,
        MindfulnessExercisesFrequency: 5,
      },
      {
        Name: 'Jordan Lee',
        Email: 'jordan.lee@example.com',
        Password: 'password789',
        Therapist: 3,
        MoodScale: 5,
        PanicButton: true,
        CBTExercisesFrequency: 4,
        MindfulnessExercisesFrequency: 3,
      },
      {
        Name: 'Casey Smith',
        Email: 'casey.smith@example.com',
        Password: 'password101112',
        Therapist: 4,
        MoodScale: 2,
        PanicButton: false,
        CBTExercisesFrequency: 5,
        MindfulnessExercisesFrequency: 2,
      },
      {
        Name: 'Jamie Brown',
        Email: 'jamie.brown@example.com',
        Password: 'password131415',
        Therapist: 5,
        MoodScale: 1,
        PanicButton: true,
        CBTExercisesFrequency: 1,
        MindfulnessExercisesFrequency: 1,
      },
    ],
    Exercises: [
      {
        Title: 'Breathing for Relaxation',
        Description:
          'A simple exercise focusing on deep, slow breathing to aid in relaxation and reduce stress.',
        Type: 'Mindfulness',
        Duration: 10,
        DifficultyLevel: 'Beginner',
      },
      {
        Title: 'Gratitude Journaling',
        Description:
          'Writing down things you are grateful for each day to improve mood and overall mental health.',
        Type: 'CBT',
        Duration: 15,
        DifficultyLevel: 'Beginner',
      },
      {
        Title: 'Progressive Muscle Relaxation',
        Description:
          'Tense and then slowly relax each muscle group in the body to reduce stress and anxiety.',
        Type: 'Mindfulness',
        Duration: 20,
        DifficultyLevel: 'Intermediate',
      },
      {
        Title: 'Thought Record',
        Description:
          'Identify negative thoughts, analyze the evidence for and against these thoughts, and come up with a more balanced thought.',
        Type: 'CBT',
        Duration: 30,
        DifficultyLevel: 'Intermediate',
      },
      {
        Title: 'Mindful Walking',
        Description:
          'Walking slowly and deliberately, paying attention to the sensation of each step, to increase mindfulness and reduce stress.',
        Type: 'Mindfulness',
        Duration: 15,
        DifficultyLevel: 'Advanced',
      },
    ],
    MoodEntries: [
      {
        Client: 1,
        Date: '2023-04-01T08:30:00',
        MoodScaleValue: 5,
        Notes: 'Feeling optimistic about the progress.',
      },
      {
        Client: 2,
        Date: '2023-04-02T09:45:00',
        MoodScaleValue: 3,
        Notes: 'Struggled with anxiety today, but managed to stay productive.',
      },
      {
        Client: 3,
        Date: '2023-04-03T10:15:00',
        MoodScaleValue: 7,
        Notes: 'Great day! Felt very calm and focused.',
      },
      {
        Client: 4,
        Date: '2023-04-04T11:00:00',
        MoodScaleValue: 2,
        Notes:
          'Had a panic attack in the morning. Used the panic button feature.',
      },
      {
        Client: 5,
        Date: '2023-04-05T12:30:00',
        MoodScaleValue: 8,
        Notes: "Feeling very positive after today's session.",
      },
    ],
  },
};
export default data;
